# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  required_workflows:
    main.yaml: False
    rebuild.yaml: False
  versions:
    rebuild: False
  codespell:
    ignore_re:
      - ^contribs/gmf/test/spec/data/themescapabilities\.js$
      - ^contribs/gmf/test/spec/data/themes\.js$
      - ^buildtools/asitvd.capabilities\.xml$
      - ^examples/measure\.js$
      - ^src/bootstrap-custom\.css\.map$

audit:
  npm:
    package_ignore:
      - webpack-dev-server
      - typedoc
      - node-sass
      - webpack-cli
      - angular-gettext-tools
      - '@storybook/core'
      - webpack
      - i18next-parser
      - '@storybook/web-components'
      - fast-sass-loader
