checks:
  required_workflows:
    main.yaml: False
    rebuild.yaml: False
  versions: False
  codespell:
    ignore_re:
      - ^contribs/gmf/test/spec/data/themescapabilities\.js$
      - ^contribs/gmf/test/spec/data/themes\.js$
      - ^buildtools/asitvd.capabilities\.xml$

audit:
  npm:
    cwe_ignore:
      - CWE-400
