---

name: Lint pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint pull request title
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
      - run: echo Actor ${{ github.actor }}

      - uses: morrisoncole/pr-lint-action@v1.4.1
        with:
          title-regex: "^(\\[.*\\] )?[A-Z0-9].*"
          on-failed-regex-comment: "The title should start with a capital (regex: %regex%)."
          on-failed-regex-create-review: false
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
        if: github.actor != 'dependabot-preview[bot]'

      - name: Update status
        uses: ouzi-dev/commit-status-updater@v1.0.0
        with:
          status: error
          description: Global status
          name: Pull request title
        if: failure()
      - name: Update status
        uses: ouzi-dev/commit-status-updater@v1.0.0
        with:
          status: success
          description: Global status
          name: Pull request title
