name: Pull request title check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    name: Pull request title check
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: morrisoncole/pr-lint-action@v1.5.1
        with:
          title-regex: "^(\\[.*\\] )?[A-Z0-9].*"
          on-failed-regex-comment: 'The title should start with a capital (regex: %regex%).'
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: false
          repo-token: 'unneeded'
        if: github.actor != 'dependabot-preview[bot]'

      # Do spell on pull request title
      - uses: actions/checkout@v2

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user codespell

      - run: jq -r '.pull_request.title' ${GITHUB_EVENT_PATH} > pull-request-title
      - run: codespell --ignore-words=spell-ignore-words.txt pull-request-title
